"use client"

import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Test Next App',
  description: 'Generated by create next app',
}

import { StoreProvider } from 'easy-peasy';
import store from '@/store/index'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StoreProvider store={store}>
        <body className={inter.className}>{children}</body>
      </StoreProvider>
    </html>
  )
}
